version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/wkfl"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 28
  - package-ecosystem: "cargo"
    directory: "/wkfl-app/src-tauri"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 28
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 28
  - package-ecosystem: "npm"
    directory: "/wkfl-app"
    schedule:
      interval: "monthly"
    groups:
      all-dependencies:
        patterns:
          - '*'
    cooldown:
      default-days: 28
